---
title: "Figure3b"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Hierarchical clustering
```{r echo = T, results = 'hide', warning=FALSE, message=FALSE}
library(tidyverse)
library(cluster)        # general clustering algorithms
library(factoextra)     # visualizing cluster results
library(dendextend)     # dendrogram
library(ggplot2)        # data visualization
library(dplyr)          # data manipulation
library(ape)
library(patchwork)
library(pheatmap)
library(RColorBrewer)
library(gplots)
```


```{r echo = T, results = 'hide', warning=FALSE, message=FALSE}

# Loading data
data <- read.csv("~/Users/cesaraugusto/Desktop/impact evaluations/2_IE_analysis/data/out/chapter1_onlyCAL_MachineLearning_Data_10052023.csv")
str(data)
data <- as.data.frame(data) # converting to data frame


# Use dplyr and tidyr to create dummy variables of ie_d
data <- data %>%
  mutate(ie_d1 = ifelse(ie_d == 1, 1, 0),
         ie_d2 = ifelse(ie_d == 2, 1, 0))


```



```{r echo = T}
par(mar = c(0.4, 4, 0.2, 0.1)) 

#make this example reproducible
set.seed(0103)


# Dissimilarity or distance matrix (Note: Dissimilarity or dissimilarity between individual points)
data.distMat <- dist(scale(data[, 14:96]), method = "euclidean")   # Euclidean distance matrix with scaling; Scaling assures that all data columns have a mean of 0 and standard deviation of 1.
# we will not include experimental studies for now since they are so different.


# Clustering distance measure (Note: distance metric between clusters, not between individual points)
hc <- hclust(data.distMat, method = "ward.D")

    # Heights
    height_values <- hc[["height"]]
    
    breaks <- seq(0, 2, by = 0.1)
    hist(height_values, ylim = c(0,700), xlab = "Height", main = NA)
    freq1 <- hist(height_values, ylim = c(0,700), xlab = "Height", main = NA)

        # Adjust breaks and xlim based on the range of your data
        breaks <- seq(floor(min(height_values)), ceiling(max(height_values)), by = 0.1)
        hist(height_values, breaks = breaks, xlim = c(0, 2), labels = TRUE, xlab = "Height")
        H1 = hist(height_values, breaks = breaks, xlim = c(0, 2), labels = TRUE, xlab = "Height")
        BarLabels = H1$counts
        BarLabels[BarLabels == 0] = ""
        hist(height_values, breaks = breaks, xlim = c(0, 3), ylim = c(0,700), labels = BarLabels, xlab = "Height", main = NA, ylab = NA)
        freq2 <-  hist(height_values, breaks = breaks, xlim = c(0, 3), ylim = c(0,700), labels = BarLabels, xlab = "Height", main = NA, ylab = NA)

        

# Dendrogram
dendro <- plot(hc, labels=FALSE, hang=-1, cex = 0.06, xlab = NA, main = NA, sub = NA)
plot(hc, labels=FALSE, hang=-1, cex = 0.6, xlab = NA, main = NA, sub = NA)


    # Visualizing the results
    hcd <- as.dendrogram(hc)
    labels_colors(hcd) <- "white"
    plot(hcd, type = "rectangle", ylab = "Height", ylim = c(0,10))
    
    # other plots
    plot(as.phylo(hc), type = "fan")
    

suppressPackageStartupMessages(library(dendextend))

avg_col_dend <- color_branches(hcd, h=0)
dendro2 <- plot(avg_col_dend, xlab="Height")
plot(avg_col_dend, xlab="Height")
plot(avg_col_dend, ylim = c(0,2), xlim=c(20, 50))


# Number of clusters by height and k (see below)
height = 0
num_clus = 45

# Dendogram with red height around the specified height
#rect.hclust(hc, h = height, border="red")

# Assigning clusters
height_values                       # Height values: 0, 2.832434, 2.977015, 3.028594, 3.042650, 3.324448, 3.493875
clusters1 <- cutree(hc, h = height) # height = 0
clusters2 <- cutree(hc, h = 2.84)   # height = 2.832434
clusters3 <- cutree(hc, h = 2.98)   # height = 2.977015
clusters4 <- cutree(hc, h = 3.03)   # height = 3.028594
clusters5 <- cutree(hc, h = 3.05)   # height = 3.042650
clusters6 <- cutree(hc, h = 3.33)   # height = 3.324448
clusters7 <- cutree(hc, h = 3.50)   # height = 3.493875


# Append clusters to original data
clustered_data <- mutate(data, cluster1 = clusters1)
clustered_data <- mutate(clustered_data, cluster2 = clusters2)
clustered_data <- mutate(clustered_data, cluster3 = clusters3)
clustered_data <- mutate(clustered_data, cluster4 = clusters4)
clustered_data <- mutate(clustered_data, cluster5 = clusters5)
clustered_data <- mutate(clustered_data, cluster6 = clusters6)
clustered_data <- mutate(clustered_data, cluster7 = clusters7)
count(clustered_data, cluster1)


# Saving data
write.csv(clustered_data, "~/Users/cesaraugusto/Desktop/impact evaluations/2_IE_analysis/data/out/chapter1_onlyCAL_MachineLearning_Data_10052023_clusters.csv")


# Step 1: Call the pdf command to start the plot
pdf(file = "~/Users/cesaraugusto/Desktop/impact evaluations/2_IE_analysis/data/out/ClusteringTree.pdf")

layout(matrix(c(1,1,
                1,1,
                2,3), ncol=2, byrow=TRUE), respect = TRUE) 
plot(avg_col_dend, hang=-1, cex = 0.6, xlab = NA, ylab="Height", main = NA, sub = NA)
text(700, 280, "A", cex=2)
par(mar = c(4, 4, 0.1, 0.1)) 
hist(height_values, ylim = c(0,700), xlab = "Height", main = NA)
text(280, 650, "B", cex=2)
hist(height_values, breaks = breaks, xlim = c(0, 3), ylim = c(0,700), xlab = "Height", main = NA, ylab = NA)
text(2.6, 650, "C", cex=2)


# Step 3: Run dev.off() to create the file!
dev.off()

pheatmap(data.distMat, 
         cluster_rows = hc,
         cluster_cols = FALSE,  # Do not cluster columns
         scale = "none",  # Data is already scaled
         show_rownames = FALSE,
         main = "Heatmap of Study Characteristics and Outcomes",
         legend = TRUE,  # Show legend
         legend_position = "left",  # Position legend on the left
         cutree_rows = 6,  # Number of clusters for rows to show in dendrogra
         clustering_method = "ward.D2",  # Clustering method for rows
         clustering_distance_rows = "euclidean",  # Distance metric for row clustering
         clustering_distance_cols = NULL,  # No clustering for columns
         show_colnames = TRUE,  # Show column names (usually row names in heatmap)
         color = colorRampPalette(brewer.pal(n = 7, 
                                                 name = "Reds"))(100),
         angle_col = 90)  # Rotate column labels by 180 degrees


```

# Removing duplicates

```{r echo = T}
# Assuming 'data' is already loaded as a dataframe

# Removing duplicated columns
data2 <- data %>% distinct(.keep_all = TRUE)

# Convert categorical variables to factors and then to numeric
data2 <- data2 %>%
  mutate(across(where(is.character), as.factor)) %>%
  mutate(across(where(is.factor), as.numeric))

# Exclude the 'key' and other non-relevant variables for scaling
data_for_scaling <- data2 %>% select(-key, -key_original, -ie_d, -outcome, -outcome_num, -outcome_group, -outcome_choice2, -outcome_choice, -irrig_program, -scale, -estimand, -horizon, -unit)

# Scale the data
scaled_data2 <- scale(data_for_scaling)

# Add 'key' as row names to maintain identification
rownames(scaled_data2) <- data2$key

# Calculate the number of studies (rows in your dataset)
num_studies <- nrow(scaled_data2)


# Compute the Euclidean distance matrix
dist_matrix2 <- dist(scaled_data2, method = "euclidean")

# Perform hierarchical clustering using Ward's method
hc_2 <- hclust(dist_matrix2, method = "ward.D2")


# Create the heatmap
pheatmap(scaled_data2, 
         cluster_rows = hc_2, 
         cluster_cols = FALSE,  # Do not cluster columns
         scale = "none",  # Data is already scaled
         show_rownames = FALSE,
         main = "Heatmap of Study Characteristics and Outcomes",
         cellwidth = 10)  # Adjust cell width as needed


# Separate by study characteristics
pheatmap(scaled_data2, 
         cluster_rows = hc_2,
         cluster_cols = FALSE,  # Do not cluster columns
         scale = "none",  # Data is already scaled
         show_rownames = FALSE,
         main = "Heatmap of Study Characteristics and Outcomes",
         legend = TRUE,  # Show legend
         legend_position = "left",  # Position legend on the left
         cutree_rows = 6,  # Number of clusters for rows to show in dendrogra
         clustering_method = "ward.D2",  # Clustering method for rows
         clustering_distance_rows = "euclidean",  # Distance metric for row clustering
         clustering_distance_cols = NULL,  # No clustering for columns
         show_colnames = TRUE,  # Show column names (usually row names in heatmap)
         angle_col = 90,
         color = colorRampPalette(brewer.pal(n = 7, 
                                                 name = "Reds"))(100))  # Rotate column labels by 180 degrees

# Dendrogram
out2 <- pheatmap(scaled_data2, 
         cluster_rows = hc_2,
         cluster_cols = FALSE,  # Do not cluster columns
         scale = "none",  # Data is already scaled
         show_rownames = FALSE,
         main = "Heatmap of Study Characteristics and Outcomes",
         legend = TRUE,  # Show legend
         legend_position = "left",  # Position legend on the left
         cutree_rows = 6,  # Number of clusters for rows to show in dendrogra
         clustering_method = "ward.D2",  # Clustering method for rows
         clustering_distance_rows = "euclidean",  # Distance metric for row clustering
         clustering_distance_cols = NULL,  # No clustering for columns
         show_colnames = TRUE,  # Show column names (usually row names in heatmap)
         color = colorRampPalette(brewer.pal(n = 7, 
                                                 name = "Reds"))(100),
         angle_col = 90)  # Rotate column labels by 180 degrees

plot(out2$tree_row, labels=FALSE, hang=-1, cex = 0.6, xlab = NA, main = NA, sub = NA)

```


## Heatmap

```{r echo = T}
# Assuming 'data' is already loaded as a dataframe

# Subset the data to include only the relevant columns
subset_data <- data %>%
  select(key, outcome_choice2, ie_d, irrig_program, scale, estimand, horizon, unit)


# Convert categorical variables to factors and then to numeric
subset_data <- subset_data %>%
  mutate(across(where(is.character), as.factor)) %>%
  mutate(across(where(is.factor), as.numeric))

# Exclude the 'key' and 'outcome_choice2' columns for scaling
data_for_scaling <- subset_data %>% select(-key)

# Scale the data
scaled_data <- scale(data_for_scaling)

# Add 'key' as row names to maintain identification
rownames(scaled_data) <- subset_data$key

# Calculate the number of studies (rows in your dataset)
num_studies <- nrow(scaled_data)


# Compute the Euclidean distance matrix
dist_matrix <- dist(scaled_data, method = "euclidean")

# Perform hierarchical clustering using Ward's method
hc3 <- hclust(dist_matrix, method = "ward.D2")


# Create the heatmap
pheatmap(scaled_data, 
         cluster_rows = hc3, 
         cluster_cols = FALSE,  # Do not cluster columns
         scale = "none",  # Data is already scaled
         show_rownames = FALSE,
         main = "Heatmap of outcomes and study characteristics",
         cellwidth = 10)  # Adjust cell width as needed


# Separate by study characteristics
pheatmap(scaled_data, 
         cluster_rows = hc3,
         cluster_cols = FALSE,  # Do not cluster columns
         scale = "none",  # Data is already scaled
         show_rownames = FALSE,
         main = "Heatmap of outcomes and study characteristics",
         cellwidth = 10,  # Adjust cell width as needed
         legend = TRUE,  # Show legend
         legend_position = "left",  # Position legend on the left
         legend_rot = 90,  # Rotate legend labels by 90 degrees
         cutree_rows = 6,  # Number of clusters for rows to show in dendrogra
         clustering_method = "ward.D2",  # Clustering method for rows
         clustering_distance_rows = "euclidean",  # Distance metric for row clustering
         clustering_distance_cols = NULL,  # No clustering for columns
         show_colnames = TRUE,  # Show column names (usually row names in heatmap)
         angle_col = 90)  # Rotate column labels by 180 degrees




# Separate by study characteristics
pheatmap(scaled_data, 
         cluster_rows = hc3,
         cluster_cols = FALSE,  # Do not cluster columns
         scale = "none",  # Data is already scaled
         show_rownames = FALSE,
         main = "Heatmap of outcomes and study characteristics",
         cellwidth = 10,  # Adjust cell width as needed
         legend = TRUE,  # Show legend
         legend_position = "left",  # Position legend on the left
         legend_rot = 90,  # Rotate legend labels by 90 degrees
         cutree_rows = 6,  # Number of clusters for rows to show in dendrogra
         clustering_method = "ward.D2",  # Clustering method for rows
         clustering_distance_rows = "euclidean",  # Distance metric for row clustering
         clustering_distance_cols = NULL,  # No clustering for columns
         show_colnames = TRUE,  # Show column names (usually row names in heatmap)
         angle_col = 90,  # Rotate column labels by 180 degrees
         color = colorRampPalette(rev(brewer.pal(n = 7, 
                                                 name = "RdYlBu")))(100))


# Separate by study characteristics
pheatmap(scaled_data, 
         cluster_rows = hc3,
         cluster_cols = FALSE,  # Do not cluster columns
         scale = "none",  # Data is already scaled
         show_rownames = FALSE,
         main = "Heatmap of outcomes and study characteristics",
         cellwidth = 10,  # Adjust cell width as needed
         legend = TRUE,  # Show legend
         legend_position = "left",  # Position legend on the left
         legend_rot = 90,  # Rotate legend labels by 90 degrees
         cutree_rows = 6,  # Number of clusters for rows to show in dendrogra
         clustering_method = "ward.D2",  # Clustering method for rows
         clustering_distance_rows = "euclidean",  # Distance metric for row clustering
         clustering_distance_cols = NULL,  # No clustering for columns
         show_colnames = TRUE,  # Show column names (usually row names in heatmap)
         angle_col = 90,  # Rotate column labels by 180 degrees
         color = colorRampPalette(rev(brewer.pal(n = 7, 
                                                 name = "BrBG")))(100))



# Create the heatmap
heatmap <- pheatmap(scaled_data, 
                    cluster_rows = hc3,
                    cluster_cols = FALSE,  # Do not cluster columns
                    scale = "none",  # Data is already scaled
                    show_rownames = FALSE,
                    main = "Heatmap of outcomes and study characteristics",
                    cellwidth = 10,  # Adjust cell width as needed
                    legend = TRUE,  # Show legend
                    legend_position = "left",  # Position legend on the left
                    legend_rot = 90,  # Rotate legend labels by 90 degrees
                    cutree_rows = 6,  # Number of clusters for rows to show in dendrogram
                    clustering_method = "ward.D2",  # Clustering method for rows
                    clustering_distance_rows = "euclidean",  # Distance metric for row clustering
                    clustering_distance_cols = NULL,  # No clustering for columns
                    show_colnames = TRUE,  # Show column names (usually row names in heatmap)
                    angle_col = 90,  # Rotate column labels by 90 degrees
                    color = colorRampPalette(rev(brewer.pal(n = 7, name = "BrBG")))(100))

# Display the updated heatmap
print(heatmap)







# Labels

# Define custom labels for columns
column_labels <- c("Outcome category", "Evaluation design", "Intervention", "Infrastructure scale", "Treatment effect estimand", "Time frame", "Unit of observation")


# heatmap
# Separate by study characteristics
pheatmap(scaled_data, 
         cluster_rows = hc3,
         cluster_cols = FALSE,  # Do not cluster columns
         scale = "none",  # Data is already scaled
         show_rownames = FALSE,
         main = "Heatmap of outcomes and study characteristics",
         cellwidth = 10,  # Adjust cell width as needed
         legend = TRUE,  # Show legend
         legend_position = "left",  # Position legend on the left
         legend_rot = 90,  # Rotate legend labels by 90 degrees
         cutree_rows = 6,  # Number of clusters for rows to show in dendrogra
         clustering_method = "ward.D2",  # Clustering method for rows
         clustering_distance_rows = "euclidean",  # Distance metric for row clustering
         clustering_distance_cols = NULL,  # No clustering for columns
         show_colnames = TRUE,  # Show column names (usually row names in heatmap)
         angle_col = 90,  # Rotate column labels by 180 degrees
         color = colorRampPalette(rev(brewer.pal(n = 7, 
                                                 name = "BrBG")))(100),
          labels_col = column_labels)



# heatmap
# Separate by study characteristics
pheatmap(scaled_data, 
         cluster_rows = hc3,
         cluster_cols = FALSE,  # Do not cluster columns
         scale = "none",  # Data is already scaled
         show_rownames = FALSE,
         main = "Heatmap of outcomes and study characteristics",
         cellwidth = 10,  # Adjust cell width as needed
         legend = TRUE,  # Show legend
         legend_position = "left",  # Position legend on the left
         legend_rot = 90,  # Rotate legend labels by 90 degrees
         cutree_rows = 6,  # Number of clusters for rows to show in dendrogra
         clustering_method = "ward.D2",  # Clustering method for rows
         clustering_distance_rows = "euclidean",  # Distance metric for row clustering
         clustering_distance_cols = NULL,  # No clustering for columns
         show_colnames = TRUE,  # Show column names (usually row names in heatmap)
         angle_col = 90,  # Rotate column labels by 180 degrees
         color = colorRampPalette(rev(brewer.pal(n = 7, 
                                                 name = "RdYlBu")))(100),
          labels_col = column_labels)



# Dendrogram
out <- pheatmap(scaled_data, 
         cluster_rows = hc3,
         cluster_cols = FALSE,  # Do not cluster columns
         scale = "none",  # Data is already scaled
         show_rownames = FALSE,
         cellwidth = 10,  # Adjust cell width as needed
         legend = TRUE,  # Show legend
         legend_position = "left",  # Position legend on the left
         legend_rot = 90,  # Rotate legend labels by 90 degrees
         cutree_rows = 6,  # Number of clusters for rows to show in dendrogra
         clustering_method = "ward.D2",  # Clustering method for rows
         clustering_distance_rows = "euclidean",  # Distance metric for row clustering
         clustering_distance_cols = NULL,  # No clustering for columns
         show_colnames = TRUE,  # Show column names (usually row names in heatmap)
         angle_col = 90,  # Rotate column labels by 180 degrees
         color = colorRampPalette(rev(brewer.pal(n = 7, 
                                                 name = "RdYlBu")))(100),
          labels_col = column_labels)


plot(out$tree_row, labels=FALSE, hang=-1, cex = 0.6, xlab = NA, main = NA, sub = NA)


heatmap.2(as.matrix(scaled_data), 
          Rowv = as.dendrogram(hc3),  # Row clustering using dendrogram object
          Colv = NA,  # Do not cluster columns
          dendrogram = "row",  # Show dendrogram for rows
          scale = "none",  # Data is already scaled
          trace = "none",  # Do not show trace lines
          key = TRUE,  # Include color key
          margins = c(5, 10),  # Adjust margins for row and column labels
          main = "Heatmap of Study Characteristics and Outcomes",
          labCol = column_labels,
          col = colorRampPalette(rev(brewer.pal(n = 7, 
                                                 name = "RdYlBu")))(100),
          density.info = "none")




heatmap.2(t(as.matrix(scaled_data)), 
          Rowv = NA,  # Row clustering using dendrogram object
          as.dendrogram(hc3),
          dendrogram = "column",  # Show dendrogram for columns
          scale = "none",  # Data is already scaled
          trace = "none",  # Do not show trace lines
          key = TRUE,  # Include color key
          key.title = "",
          key.xlab = "",
          margins = c(1, 10),  # Adjust margins for row and column labels
          labRow = column_labels,
          labCol = FALSE,
          col = colorRampPalette(rev(brewer.pal(n = 7, 
                                                name = "RdYlBu")))(100),
          density.info = "none",
          cexRow = 1.1,
          offsetRow = 0.5,
          keysize = 1.1,
          lmat = rbind(c(2,3,4), c(2,3,3), c(0,1,1)), lwid=c(0.5,7,4), lhei = c(3,0.2,3))

# Add the letter "b" at the top-left corner
text(x = -0.052, y = 2.3, labels = "b", xpd = NA, cex = 1.5, font = 2)


hierar_fig <- heatmap.2(t(as.matrix(scaled_data)), 
          Rowv = NA,  # Row clustering using dendrogram object
          as.dendrogram(hc3),
          dendrogram = "column",  # Show dendrogram for columns
          scale = "none",  # Data is already scaled
          trace = "none",  # Do not show trace lines
          key = TRUE,  # Include color key
          key.title = "",
          key.xlab = "",
          margins = c(1, 12),  # Adjust margins for row and column labels
          labRow = column_labels,
          labCol = FALSE,
          col = colorRampPalette(rev(brewer.pal(n = 7, 
                                                name = "RdYlBu")))(100),
          density.info = "none",
          cexRow = 1.1,
          offsetRow = 0.5,
          keysize = 1.1,
          lmat = rbind(c(2,3,4), c(2,3,3), c(0,1,1)), lwid=c(0.2,7,4), lhei = c(3,0.2,3.5))

# Adjust the x and y values to move the label
x_pos <- par("usr")[1] - 0.15   # Move left
y_pos <- par("usr")[4] + 1.05      # Move up

# Overlay the letter 'b' with adjusted position
text(x = x_pos, y = y_pos, labels = "b", 
     adj = c(0, 1), xpd = TRUE, cex = 1.5, font = 2)


dev.off()

```



